language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install -e .[deploy]
script:
  - pytest


before_deploy:
  - "if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then make apidoc; make html;fi"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: doc/_build/html
  on:
    branch: master
    python: 3.5