# configure a etherpad server that uses a mysql db (hosted in a separate
# container) as a backend
#
# This config uses 'named' external volumes for storing the persistent data.
# These are managed with the 'docker volume' command.
python:

    build: "python"

    # TCP redirection: redirect port 9001 of the local host to the 9001 port of
    # the container
    ports:
        - "8888:8888"

    volumes:
        # store the var directory into the 'out' volume
        - highway-out:/home/user/highway-env/scenarios/out